services:
  - type: web
    name: flask-playwright-app
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
